-- MySQL Script generated by MySQL Workbench
-- 03/23/16 17:47:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tramitedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tramitedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tramitedb` DEFAULT CHARACTER SET utf8 ;
USE `tramitedb` ;

-- -----------------------------------------------------
-- Table `tramitedb`.`solicitante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tramitedb`.`solicitante` (
  `id_solicitante` INT(11) NOT NULL,
  `dni_solicitante` VARCHAR(8) NULL,
  `nom_solicitante` VARCHAR(45) NULL,
  `ape_solicitante` VARCHAR(45) NULL,
  `login_solicitante` VARCHAR(45) NULL,
  `pass_solicitante` VARCHAR(45) NULL,
  PRIMARY KEY (`id_solicitante`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tramitedb`.`tipodoc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tramitedb`.`tipodoc` (
  `id_tipodoc` INT(11) NOT NULL,
  `desc_tipodoc` VARCHAR(20) NULL,
  `plazo_tipodoc` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipodoc`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tramitedb`.`documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tramitedb`.`documento` (
  `id_documento` INT(11) NOT NULL AUTO_INCREMENT,
  `nro_documento` VARCHAR(30) NULL,
  `fecha_creacion_documento` DATE NULL DEFAULT NULL,
  `sumilla_documento` VARCHAR(20) NULL DEFAULT NULL,
  `estado_documento` VARCHAR(20) NULL DEFAULT NULL,
  `id_solicitante` INT(11) NOT NULL,
  `id_tipo_doc` INT(11) NOT NULL,
  PRIMARY KEY (`id_documento`),
  INDEX `fk_Documento_Solicitante1_idx` (`id_solicitante` ASC),
  INDEX `fk_Documento_TipoDocumento1_idx` (`id_tipo_doc` ASC),
  CONSTRAINT `fk_Documento_Solicitante1`
    FOREIGN KEY (`id_solicitante`)
    REFERENCES `tramitedb`.`solicitante` (`id_solicitante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Documento_TipoDocumento1`
    FOREIGN KEY (`id_tipo_doc`)
    REFERENCES `tramitedb`.`tipodoc` (`id_tipodoc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tramitedb`.`adjundoc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tramitedb`.`adjundoc` (
  `id_adjun_doc` INT NOT NULL AUTO_INCREMENT,
  `fecha_adjun_doc` DATE NULL DEFAULT NULL,
  `detalle_adjun_doc` VARCHAR(45) NULL,
  `id_documento` INT(11) NOT NULL,
  PRIMARY KEY (`id_adjun_doc`),
  INDEX `fk_AdjunDocumento_Documento1_idx` (`id_documento` ASC),
  CONSTRAINT `fk_AdjunDocumento_Documento1`
    FOREIGN KEY (`id_documento`)
    REFERENCES `tramitedb`.`documento` (`id_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tramitedb`.`area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tramitedb`.`area` (
  `id_area` INT(11) NOT NULL AUTO_INCREMENT,
  `desc_area` VARCHAR(25) NULL,
  PRIMARY KEY (`id_area`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tramitedb`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tramitedb`.`cargo` (
  `id_cargo` INT(11) NOT NULL AUTO_INCREMENT,
  `desc_cargo` VARCHAR(25) NULL,
  PRIMARY KEY (`id_cargo`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tramitedb`.`tipousu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tramitedb`.`tipousu` (
  `id_tipo_usu` INT(11) NOT NULL AUTO_INCREMENT,
  `desc_tipo_usu` VARCHAR(15) NULL,
  PRIMARY KEY (`id_tipo_usu`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tramitedb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tramitedb`.`usuario` (
  `id_usuario` INT(11) NOT NULL,
  `id_cargo` INT(11) NOT NULL,
  `id_crea` INT(11) NOT NULL,
  `id_tipousu` INT(11) NOT NULL,
  `nom_usuario` VARCHAR(45) NULL,
  `ape_usuario` VARCHAR(45) NULL,
  `dni_usuario` VARCHAR(45) NULL,
  `login_usuario` VARCHAR(45) NULL,
  `pass_usuario` VARCHAR(45) NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_Usuario_Cargo_idx` (`id_cargo` ASC),
  INDEX `fk_Usuario_Area1_idx` (`id_crea` ASC),
  INDEX `fk_Usuario_TipoUsu1_idx` (`id_tipousu` ASC),
  CONSTRAINT `fk_Usuario_Area1`
    FOREIGN KEY (`id_crea`)
    REFERENCES `tramitedb`.`area` (`id_area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Cargo`
    FOREIGN KEY (`id_cargo`)
    REFERENCES `tramitedb`.`cargo` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_TipoUsu1`
    FOREIGN KEY (`id_tipousu`)
    REFERENCES `tramitedb`.`tipousu` (`id_tipo_usu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tramitedb`.`registrodoc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tramitedb`.`registrodoc` (
  `id_registro_doc` INT(11) NOT NULL,
  `desc_rpta_registro_doc` VARCHAR(45) NULL,
  `fecha_envio_registro_doc` DATE NULL DEFAULT NULL,
  `fecha_recepcion_registro_doc` DATE NULL DEFAULT NULL,
  `fecha_visto_registro_doc` DATE NULL DEFAULT NULL,
  `id_documento` INT(11) NOT NULL,
  `id_usuario_ini` INT(11) NOT NULL,
  `id_usuario_dest` INT(11) NOT NULL,
  PRIMARY KEY (`id_registro_doc`),
  INDEX `fk_RegDoc_Documento1_idx` (`id_documento` ASC),
  INDEX `fk_RegistroDoc_Usuario1_idx` (`id_usuario_ini` ASC),
  INDEX `fk_RegistroDoc_Usuario2_idx` (`id_usuario_dest` ASC),
  CONSTRAINT `fk_RegDoc_Documento1`
    FOREIGN KEY (`id_documento`)
    REFERENCES `tramitedb`.`documento` (`id_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RegistroDoc_Usuario1`
    FOREIGN KEY (`id_usuario_ini`)
    REFERENCES `tramitedb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RegistroDoc_Usuario2`
    FOREIGN KEY (`id_usuario_dest`)
    REFERENCES `tramitedb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
